
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check rust install
      run: |
        rustup update
        rustc --version
        rustup toolchain list

    - name: Install requirements
      working-directory: ./whvp-py
      run: |
        pip install -r requirements.txt

    - name: Build wheels
      working-directory: ./whvp-py
      env:
        LIBCLANG_PATH: C:\Program Files\LLVM\bin
      run: |
        maturin build --release
        
    - name: Upload wheels
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./whvp-py/target/wheels

